name: CI Workflow for Multi-Project Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ui_testing:
    name: UI Testing
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust based on your project requirements
          distribution: 'temurin'

      # Run UI Testing project
      - name: Run UI Tests
        working-directory: UI_Testing
        run: |
          mvn clean install
          mvn test

  api_testing:
    name: API Testing
    runs-on: ubuntu-latest
    needs: ui_testing # Ensures UI tests run first (optional; remove if not required)

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust based on your project requirements
          distribution: 'temurin'

      # Run API Testing project
      - name: Run API Tests
        working-directory: API_Testing
        run: |
          mvn clean install
          mvn test

