name: CI Workflow for Multi-Project Repository

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ui_testing:
    name: UI Testing
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment (JDK 21)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Adjust based on your project requirements
          distribution: 'temurin'

      # Install Google Chrome and ChromeDriver
      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Install ChromeDriver (ensure compatibility with Chrome version)
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | sed 's/\./_/g')
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      # Run UI Testing project
      - name: Run UI Tests
        working-directory: UI_Testing
        run: |
          mvn clean install
          mvn test

  api_testing:
    name: API Testing
    runs-on: ubuntu-latest
    needs: ui_testing # Ensures UI tests run first (optional; remove if not required)

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment (JDK 21)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Adjust based on your project requirements
          distribution: 'temurin'

      # Run API Testing project
      - name: Run API Tests
        working-directory: API_Testing
        run: |
          mvn clean install
          mvn test
