name: CI Workflow for Multi-Project Repository

on:
  push:
    branches:
      - charuka-dev
  pull_request:
    branches:
      - charuka-dev

jobs:
  ui_testing:
    name: UI Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable -y
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Debug Chrome Setup
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run UI Tests
        working-directory: UI_Testing
        run: |
          mvn clean install
          mvn test -Dcucumber.options="--plugin pretty --plugin json:target/cucumber-report.json"

      - name: Publish Cucumber Report
        uses: actions/upl
